# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primeGUI.ui'
#
# Created: Thu Apr  2 15:47:30 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 278)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pEdit = QtGui.QLineEdit(self.centralwidget)
        self.pEdit.setGeometry(QtCore.QRect(40, 50, 601, 21))
        self.pEdit.setObjectName("pEdit")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 17))
        self.label.setObjectName("label")
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(250, 170, 111, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(250, 120, 111, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 90, 62, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 150, 62, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 121, 17))
        self.label_4.setObjectName("label_4")
        self.primeAnswer = QtGui.QTextBrowser(self.centralwidget)
        self.primeAnswer.setGeometry(QtCore.QRect(400, 90, 231, 51))
        self.primeAnswer.setObjectName("primeAnswer")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 120, 178, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brute_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.brute_checkBox.setAutoFillBackground(False)
        self.brute_checkBox.setChecked(True)
        self.brute_checkBox.setObjectName("brute_checkBox")
        self.verticalLayout.addWidget(self.brute_checkBox)
        self.miller_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.miller_checkBox.setObjectName("miller_checkBox")
        self.verticalLayout.addWidget(self.miller_checkBox)
        self.aks_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.aks_checkBox.setObjectName("aks_checkBox")
        self.verticalLayout.addWidget(self.aks_checkBox)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(450, 170, 178, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stopButton = QtGui.QPushButton(self.layoutWidget1)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.testButton = QtGui.QPushButton(self.layoutWidget1)
        self.testButton.setObjectName("testButton")
        self.horizontalLayout.addWidget(self.testButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Prime to test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Method to Test", None, QtGui.QApplication.UnicodeUTF8))
        self.brute_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Brute-Force", None, QtGui.QApplication.UnicodeUTF8))
        self.miller_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Miller-Rabin", None, QtGui.QApplication.UnicodeUTF8))
        self.aks_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Agrawal-Kayal-Saxena", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))

